### ISSUE TITLE
audio-tsne notebook cannot load all the files in Vintage Drum Machine

### ISSUE THREAD

**Issue by zfadmireyou** [ml4a/ml4a#20]
When running audio-tsne notebook, some loading error happens when loading wav files like below.

Can anyone suggestion the reason, please?

get 1 of 6153 = ../data/Vintage Drum Machines/Korg T3/Bassdrum-01.wav
error loading ../data/Vintage Drum Machines/Korg T3/Rim shot.wav
get 101 of 6153 = ../data/Vintage Drum Machines/X Drum LM8953/Snaredrum-03.wav
get 201 of 6153 = ../data/Vintage Drum Machines/Cheetah MD16/CHTMD15.wav
get 301 of 6153 = ../data/Vintage Drum Machines/Novation Drumstation/Kit07/DS07808Clave.wav
get 401 of 6153 = ../data/Vintage Drum Machines/Novation Drumstation/Kit12/DS12909Hat_O.wav
get 501 of 6153 = ../data/Vintage Drum Machines/Novation Drumstation/Kit13/DS13808CongaHi.wav
get 601 of 6153 = ../data/Vintage Drum Machines/Novation Drumstation/Kit02/DS02808CongaHi.wav
get 701 of 6153 = ../data/Vintage Drum Machines/Novation Drumstation/Kit18/DS18909Kick.wav
get 801 of 6153 = ../data/Vintage Drum Machines/Novation Drumstation/Kit10/DS10808TomMid.wav
get 901 of 6153 = ../data/Vintage Drum Machines/Roland MC-303/Cymbals/Realoh2.wav
get 1001 of 6153 = ../data/Vintage Drum Machines/Boss DR-110/DR-110Snare.wav
get 1101 of 6153 = ../data/Vintage Drum Machines/SH09 Drum sounds/909bass5.wav
get 1201 of 6153 = ../data/Vintage Drum Machines/Yamaha RY30/RY30Hat_O1.wav
get 1301 of 6153 = ../data/Vintage Drum Machines/Yamaha EX5/EX5C 010.wav
get 1401 of 6153 = ../data/Vintage Drum Machines/Boss DR-660/DR-660Hat_C06.wav
get 1501 of 6153 = ../data/Vintage Drum Machines/Boss DR-660/DR-660Perc66.wav
get 1601 of 6153 = ../data/Vintage Drum Machines/Boss DR-660/DR-660Snare14.wav
get 1701 of 6153 = ../data/Vintage Drum Machines/Quasimidi 309/QuasiA 022.wav
get 1801 of 6153 = ../data/Vintage Drum Machines/Quasimidi 309/QuasiB 111.wav
get 1901 of 6153 = ../data/Vintage Drum Machines/Boss DR-202/202per52.wav
get 2001 of 6153 = ../data/Vintage Drum Machines/Boss DR-202/202rim01.wav
get 2101 of 6153 = ../data/Vintage Drum Machines/Simmons SDS5/SDTomNoise.wav
get 2201 of 6153 = ../data/Vintage Drum Machines/Korg KPR-77/Hat Open.wav
error loading ../data/Vintage Drum Machines/Kawai K3/K3M_01.wav
error loading ../data/Vintage Drum Machines/Kawai K3/K3M_15.wav
error loading ../data/Vintage Drum Machines/Kawai K3/K3M_29.wav
error loading ../data/Vintage Drum Machines/Kawai K3/K3M_28.wav
error loading ../data/Vintage Drum Machines/Kawai K3/K3M_14.wav
error loading ../data/Vintage Drum Machines/Kawai K3/K3M_00.wav
error loading ../data/Vintage Drum Machines/Kawai K3/K3M_16.wav
error loading ../data/Vintage Drum Machines/Kawai K3/K3M_02.wav
error loading ../data/Vintage Drum Machines/Kawai K3/K3M_03.wav
error loading ../data/Vintage Drum Machines/Kawai K3/K3M_17.wav
error loading ../data/Vintage Drum Machines/Kawai K3/K3M_13.wav
error loading ../data/Vintage Drum Machines/Kawai K3/K3M_07.wav
error loading ../data/Vintage Drum Machines/Kawai K3/K3M_06.wav
error loading ../data/Vintage Drum Machines/Kawai K3/K3M_12.wav
error loading ../data/Vintage Drum Machines/Kawai K3/K3M_04.wav
error loading ../data/Vintage Drum Machines/Kawai K3/K3M_10.wav
error loading ../data/Vintage Drum Machines/Kawai K3/K3M_11.wav
error loading ../data/Vintage Drum Machines/Kawai K3/K3M_05.wav
error loading ../data/Vintage Drum Machines/Kawai K3/K3M_20.wav
error loading ../data/Vintage Drum Machines/Kawai K3/K3M_08.wav
error loading ../data/Vintage Drum Machines/Kawai K3/K3M_09.wav
error loading ../data/Vintage Drum Machines/Kawai K3/K3M_21.wav
error loading ../data/Vintage Drum Machines/Kawai K3/K3M_23.wav
error loading ../data/Vintage Drum Machines/Kawai K3/K3M_22.wav
error loading ../data/Vintage Drum Machines/Kawai K3/K3M_26.wav
error loading ../data/Vintage Drum Machines/Kawai K3/K3M_27.wav
error loading ../data/Vintage Drum Machines/Kawai K3/K3M_19.wav
error loading ../data/Vintage Drum Machines/Kawai K3/K3M_25.wav
error loading ../data/Vintage Drum Machines/Kawai K3/K3M_31.wav
error loading ../data/Vintage Drum Machines/Kawai K3/K3M_30.wav
error loading ../data/Vintage Drum Machines/Kawai K3/K3M_24.wav
error loading ../data/Vintage Drum Machines/Kawai K3/K3M_18.wav
get 2301 of 6153 = ../data/Vintage Drum Machines/Korg M1/Misc/Tubalar Bell-03.wav
get 2401 of 6153 = ../data/Vintage Drum Machines/Roland D-70/Rim Shot.wav
get 2501 of 6153 = ../data/Vintage Drum Machines/Roland R-8/R8Snare24.wav
get 2601 of 6153 = ../data/Vintage Drum Machines/Roland R-8/R8TomH2.wav
get 2701 of 6153 = ../data/Vintage Drum Machines/Roland R-8/R8Snare38.wav
get 2801 of 6153 = ../data/Vintage Drum Machines/MFB-512/512 loop.wav
get 2901 of 6153 = ../data/Vintage Drum Machines/Boss DR-550/DR550Tom02_M.wav
get 3001 of 6153 = ../data/Vintage Drum Machines/Emu SP12/Toms/Tom L-04.wav
get 3101 of 6153 = ../data/Vintage Drum Machines/Roland TR-808/TR-808Kick13.wav
get 3201 of 6153 = ../data/Vintage Drum Machines/Alesis SR-16/Snaredrums/Snaredrum-02.wav
error loading ../data/Vintage Drum Machines/Alesis SR15/sr16_toms/SR16 Tom_Elect 2.wav
error loading ../data/Vintage Drum Machines/Alesis SR15/sr16_toms/SR16 Tom_Elect 1.wav
get 3301 of 6153 = ../data/Vintage Drum Machines/Alesis SR15/sr16_kik22/SR16 Kik_Room Lo2.wav
error loading ../data/Vintage Drum Machines/Alesis SR15/sr16_kik22/SR16 Kik_Dry08.wav
error loading ../data/Vintage Drum Machines/Alesis SR15/sr16_kik22/SR16 Kik_Dry05.wav
error loading ../data/Vintage Drum Machines/Alesis SR15/sr16_kik22/SR16 Kik_Elect Hi.wav
error loading ../data/Vintage Drum Machines/Alesis SR15/sr16_perc22/SR16 Prc_Clave Hi.wav
error loading ../data/Vintage Drum Machines/Alesis SR15/sr16_perc22/SR16 Prc_Agogo Hi.wav
error loading ../data/Vintage Drum Machines/Alesis SR15/sr16_perc22/SR16 Prc_Fish Lo.wav
error loading ../data/Vintage Drum Machines/Alesis SR15/sr16_perc22/SR16 Prc_Fishstick.wav
error loading ../data/Vintage Drum Machines/Alesis SR15/sr16_perc22/SR16 Prc_Sticks Hi.wav
error loading ../data/Vintage Drum Machines/Alesis SR15/sr16_perc22/SR16 Prc_Cowbell Hi.wav
error loading ../data/Vintage Drum Machines/Alesis SR15/sr16_perc22/SR16 Prc_Cabasa.wav
error loading ../data/Vintage Drum Machines/Alesis SR15/sr16_perc22/SR16 Prc_Clave Lo.wav
error loading ../data/Vintage Drum Machines/Alesis SR15/sr16_perc22/SR16 Prc_Shaker.wav
get 3401 of 6153 = ../data/Vintage Drum Machines/Alesis SR15/sr16_snares/SR16 Snr_Dry Deep.wav
error loading ../data/Vintage Drum Machines/Alesis SR15/sr16_hats22/SR16 Hat_Vari.wav
error loading ../data/Vintage Drum Machines/Alesis SR15/sr16_hats22/SR16 Hat_Closed.wav
error loading ../data/Vintage Drum Machines/Alesis SR15/sr16_hats22/SR16 Hat_Tight.wav
error loading ../data/Vintage Drum Machines/Alesis SR15/sr16_hats22/SR16 Hat_Small.wav
get 3501 of 6153 = ../data/Vintage Drum Machines/Roland TR-626/TR-626Hat_O.wav
get 3601 of 6153 = ../data/Vintage Drum Machines/Roland S50/Cymbals/Ride.wav
get 3701 of 6153 = ../data/Vintage Drum Machines/Akai  XR-10/Percussion/Cabasa.wav
get 3801 of 6153 = ../data/Vintage Drum Machines/Yamaha TG-33/Bassdrum-03.wav
get 3901 of 6153 = ../data/Vintage Drum Machines/Linn LinnDrum/Cymbals/Hat Open.wav
get 4001 of 6153 = ../data/Vintage Drum Machines/Roland Digital Drum Brain DDR-30/Snaredrum-02.wav
error loading ../data/Vintage Drum Machines/Roland TR-505/Snaredrum.wav
error loading ../data/Vintage Drum Machines/Roland TR-505/Conga H.wav
error loading ../data/Vintage Drum Machines/Roland TR-505/Cowbell L.wav
error loading ../data/Vintage Drum Machines/Roland TR-505/Cowbell H.wav
error loading ../data/Vintage Drum Machines/Roland TR-505/Bassdrum.wav
error loading ../data/Vintage Drum Machines/Roland TR-505/Hat Closed.wav
error loading ../data/Vintage Drum Machines/Roland TR-505/Clap.wav
error loading ../data/Vintage Drum Machines/Roland TR-505/Rimshot.wav
get 4101 of 6153 = ../data/Vintage Drum Machines/Roland TR-909/TR-909Hat C 01.wav
get 4201 of 6153 = ../data/Vintage Drum Machines/Yamaha RM 50/Snaredrums/SNAREDRUM_108.wav
get 4301 of 6153 = ../data/Vintage Drum Machines/Yamaha RM 50/Cymbals/CYMBAL_005.wav
error loading ../data/Vintage Drum Machines/Yamaha RM 50/FX/FX_138.wav
get 4401 of 6153 = ../data/Vintage Drum Machines/Yamaha RM 50/FX/FX_024.wav
error loading ../data/Vintage Drum Machines/Yamaha RM 50/FX/FX_136.wav
error loading ../data/Vintage Drum Machines/Yamaha RM 50/FX/FX_137.wav
get 4501 of 6153 = ../data/Vintage Drum Machines/Yamaha RM 50/Bassdrums/BD-083.wav
get 4601 of 6153 = ../data/Vintage Drum Machines/Yamaha RM 50/Toms/TOMS_021.wav
get 4701 of 6153 = ../data/Vintage Drum Machines/Roland TR-707/Cowbell.wav
get 4801 of 6153 = ../data/Vintage Drum Machines/Rhodes Polaris/Snaredrum-03.wav
get 4901 of 6153 = ../data/Vintage Drum Machines/Alesis DM5/DM5Hat_O08.wav
get 5001 of 6153 = ../data/Vintage Drum Machines/Alesis DM5/DM5Perc018.wav
get 5101 of 6153 = ../data/Vintage Drum Machines/Alesis DM5/DM5FX23.wav
get 5201 of 6153 = ../data/Vintage Drum Machines/Alesis DM5/DM5Tom10_Lo.wav
get 5301 of 6153 = ../data/Vintage Drum Machines/Yamaha CS6/Yamaha CS6 072.wav
get 5401 of 6153 = ../data/Vintage Drum Machines/Yamaha CS6/Yamaha CS6 047.wav
get 5501 of 6153 = ../data/Vintage Drum Machines/Roland JD-990/Cowbell.wav
get 5601 of 6153 = ../data/Vintage Drum Machines/Roland JD800 Dance Card/JD800 Dance Card Drums 053.wav
get 5701 of 6153 = ../data/Vintage Drum Machines/Sequential Drumtacks/DrumTraks/DT Hat Closed.wav
get 5801 of 6153 = ../data/Vintage Drum Machines/Roland R-5/R-5 Timbale.wav
get 5901 of 6153 = ../data/Vintage Drum Machines/Roland System-100/Snaredrum-10.wav
get 6001 of 6153 = ../data/Vintage Drum Machines/Simmons SDS-5/BASSDRUM/Bassdrum-12.wav
get 6101 of 6153 = ../data/Vintage Drum Machines/Yamaha RY-30/Percussion/Woodblock-01.wav
calculated 6091 feature vectors

**Comment by genekogan** [comment]
some of them are too short to be loaded (you'll see some of them are just a few bytes of data) so they get skipped.
