### ISSUE TITLE
New query image issue

### ISSUE THREAD

**Issue by mathmax12** [ml4a/ml4a#29]
I am trying to build a CBIR system based on your work:
https://github.com/ml4a/ml4a-guides/blob/master/notebooks/image-search.ipynb
It's very useful. Thank you.

I have question about the query phase.
In this link the input of the query image is randomly picked up from the database.
So the dim-reduced features after PCA-process is used for the distance calculation to find the similar images.

What if the query image is a new image, which doesn't exist in the database?
Do we need to rebuild the feature database with the query image plus the original image database (CNN feature extraction +PCA)? And then calculate the similarity between the feature of query image and features of other images in database?

Looking forward to hearing from you.

Thanks.
Sean

**Comment by genekogan** [comment]
no, you just need to project the new image into PCA components space, i.e.
    
    newSamplePCAFeatures = pca.transform(np.array(newSampleFeatures))[0]

**Comment by mathmax12** [comment]
Thanks for help.

here is what I did 
`query_image, x = get_image("./101_ObjectCategories/airplanes/image_0002.jpg")
newSampleFeatures=feat_extractor.predict(x)[0]

newSampleFeatures_reshape=newSampleFeatures.reshape(1,-1)
pca = PCA(n_components=300)
pca.fit(newSampleFeatures_reshape)
newSamplePCAFeatures = pca.transform(np.array(newSampleFeatures_reshape))[0]
print(newSamplePCAFeatures)`

But the output is
`....Pyhon_workdirectory/lib/python3.5/site-packages/sklearn/decomposition/pca.py:423: RuntimeWarning: invalid value encountered in true_divide
  explained_variance_ = (S ** 2) / (n_samples - 1)
[0.]`

Do I miss something?

Thanks.

**Comment by mathmax12** [comment]
@genekogan 
In my understanding the size of PCA result of a matrix A(m,n) should less the max(m,n).
For "newSampleFeatures_reshape" in the last post, its size is 1x1096.
Thant means the size of the result of PCA is less than 1, right?

**Comment by genekogan** [comment]
you do not need to refit the pca. save the one you computed on the first set of points, and when you get a new point, just run pca.fit on it (using the old pca).

**Comment by mathmax12** [comment]
Thanks.
Can you explain that in more details?
I am not a expertise of Python and PCA.

Thanks.

**Comment by mathmax12** [comment]
Thanks. got it!
