### ISSUE TITLE
Images not showing

### ISSUE THREAD

**Issue by WizardOfAus** [ml4a/ml4a#42]
Some of the images uploaded for the ipy workbooks don't show

E.g. https://github.com/ml4a/ml4a-guides/blob/master/notebooks/fundamentals.ipynb is not showing the images 'Varying Lines' and 'A vector'

**Comment by augustolf** [comment]
Yes, I thinking is something about relative path of images:

//github.com/ml4a/ml4a-guides/raw/1a04c17fefc90df3a1f098291e326fd241978499/notebooks/../assets/lines.svg

//github.com/ml4a/ml4a-guides/raw/1a04c17fefc90df3a1f098291e326fd241978499/notebooks/../assets/vector.svg

**Comment by genekogan** [comment]
This is fixed.
