### ISSUE TITLE
InternalError: Error at structural_properties.c:4406: Weight vector must be non-negative

### ISSUE THREAD

**Issue by vishalkumarlondon** [ml4a/ml4a#43]
Hey Gene, when I run cell 24 in the image-path notebook, specifically, the code to get the paths between two random images, I get the following InternalError:

InternalError: Error at structural_properties.c:4406: Weight vector must be non-negative, Invalid value

Any suggestions on how I could proceed? Thanks

**Comment by genekogan** [comment]
something's wrong with your igraph library installation.

**Comment by vishalkumarlondon** [comment]
Interesting... thanks. I was, in fact, having issues installing igraph properly. I did manage to create the kNN = 30 graph, but I only get the problem when running the 'get_shortest_paths' methods. I'll take a deeper look and will revisit my igraph installation. Thank you
