### ISSUE TITLE
Drums data download fails

### ISSUE THREAD

**Issue by armadillu** [ml4a/ml4a#54]
Hi! First of all thanks for doing all of this!
I'm trying to run the examples, and downloading the required data fails here.

https://github.com/ml4a/ml4a-guides/blob/master/data/download.sh#L16

Is the file hosted somewhere else too?

**Comment by genekogan** [comment]
I don't have it -- I guess it's been taken down. Perhaps can replace it with another dataset. If you know of a good one, please suggest.
