### ISSUE TITLE
Cartoonization notebook throws shape error with other images

### ISSUE THREAD

**Issue by javipus** [ml4a/ml4a#70]
The [cartoonization notebook](https://github.com/ml4a/ml4a/blob/master/examples/models/cartoonization.ipynb) works as is, but it throws the following error when run with other images.

```
InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: Incompatible shapes: [1,182,137,64] vs. [1,182,138,64]
	 [[{{node generator/add}}]]
	 [[add_1/_75]]
  (1) Invalid argument: Incompatible shapes: [1,182,137,64] vs. [1,182,138,64]
	 [[{{node generator/add}}]]
```

The issue seems to be an off-by-one error between the width that the image is downscaled/cropped to and the width that the model expects.

**Comment by genekogan** [comment]
This has been fixed.
