### ISSUE TITLE
Issue with stylegan.dataset_tool transform parameter

### ISSUE THREAD

**Issue by Solcany** [ml4a/ml4a#71]
[I'm following this ml4a notebook](https://colab.research.google.com/github/ml4a/ml4a/blob/master/examples/models/stylegan2_ada.ipynb#scrollTo=variable-benchmark)

When I try to run this block:

```
from ml4a.models import stylegan
  
  # replace 'images_folder' and 'dataset_output' with your own locations.
  
  config = {
      'images_folder': '/pathToMyDataset/',
      'dataset_output': '/pathToDatasetDest/',
      'transform': None,
      'labels': False,
      'size': 256
  }
  
  stylegan.dataset_tool(config)
```

I get:
```
TypeError: sequence item 7: expected str instance, NoneType found
```

This error only occurs when I use 'transform': None.

**Comment by genekogan** [comment]
This should be fixed with the next update to the pip library. for now, you can fix this by installing ml4a from source, i.e.

instead of `pip install ml4a`, do `pip install git+https://github.com/ml4a/ml4a`.
