### ISSUE TITLE
neural_style notebook is no longer there 

### ISSUE THREAD

**Issue by metaphorz** [ml4a/ml4a#79]
The following URL is found, but when clicking on Colab icon, I get a 404 error.

https://colab.research.google.com/github/ml4a/ml4a/blob/master/examples/models/neural_style.ipynb

**Comment by KushGabani** [comment]
The link seems to be working just fine for me. Can you explain how can I reproduce this issue?

**Comment by metaphorz** [comment]
Maybe the issue is on my end. The above link does work correctly. The problem is then if you click on the 
OPEN-IN-COLAB blue button, there is an error (file not found). Where is the Colab notebook located? Thanks
much!

**Comment by genekogan** [comment]
apologies for the broken link, the links are correct on https://ml4a.net

**Comment by metaphorz** [comment]
Thanks Gene. Can close issue.

-paul

 

Paul Fishwick, PhD
Distinguished University Chair of Arts, Technology, and Emerging Communication
Professor of Computer Science
Director, Creative Automata Laboratory
The University of Texas at Dallas
Arts & Technology
800 West Campbell Road, AT10
Richardson, TX 75080-3021
Home: utdallas.edu/atec/fishwick
Media: ***@***.***
Modeling: digest.sigsim.org
Twitter: @PaulFishwick

ONLINE: Webex,Collaborate, TEAMS, Zoom, Skype, Hangout

 

 

From: Gene Kogan ***@***.***>
Reply-To: ml4a/ml4a ***@***.***>
Date: Tuesday, November 2, 2021 at 8:38 AM
To: ml4a/ml4a ***@***.***>
Cc: Paul Fishwick ***@***.***>, Author ***@***.***>
Subject: Re: [ml4a/ml4a] neural_style notebook is no longer there (Issue #79)

 

apologies for the broken link, the links are correct on https://ml4a.net
